spring:
  datasource:
    druid:
      url: # url
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: # username
      password: # password
      filters: stat,wall,log4j2                                # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      maxActive: 10                                     # 最大连接数
      initialSize: 1                                    # 初始化大小
      maxWait: 10000                                    # 配置获取连接等待超时的时间
      minIdle: 5                                        # 最小连接数
      timeBetweenEvictionRunsMillis: 60000              # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      minEvictableIdleTimeMillis: 300000                # 配置一个连接在池中最小生存时间
      validationQuery: SELECT 1                         # 验证语句
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true                      # 打开 PSCache
      maxPoolPreparedStatementPerConnectionSize: 20     #指定每个连接上 PSCache 的大小
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500  # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      maxOpenPreparedStatements: 20
      useGlobalDataSourceStat: true
      removeAbandoned: true     # 超过时间限制是否回收
      removeAbandonedTimeout: 180 #超时时间；单位为秒。180秒=3分钟
      logAbandoned: true #关闭abanded连接时输出错误日志
      web-stat-filter: # 配置StatFilter
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet: #配置StatViewServlet
        url-pattern: "/druid/*" # 监控页面访问路径
        allow: 127.0.0.1        #允许那些ip
        login-username: admin
        login-password: admin
        deny: 192.168.1.102   #禁止那些ip
        reset-enable: true    #是否可以重置
        enabled: true   #启用
      db-type: mysql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #日志输出
    cache-enabled: true                                      #开启Mybatis二级缓存
    use-generated-keys: true
    default-executor-type: reuse
    use-actual-param-name: true
  mapper-locations: "classpath*:/mappers/**/*.xml"